### ISSUE TITLE
Not working on mac catalina 10.15.6 (19G2021)

### ISSUE THREAD

**Issue by ctopinka** [zsh-git-prompt/zsh-git-prompt#11]
Stopped working. Switched from olivierverdier to see if that was the problem. With olivierverdier was getting nothing. Now getting

```
$(git_super_status) % 


```

**Comment by ctopinka** [comment]
```
#zsh-git-prompt installed via brew
#https://github.com/olivierverdier/zsh-git-prompt
source "~/zsh-git-prompt/zshrc.sh"
PROMPT='%B%m%~%b$(git_super_status) %# '


```

**Comment by ctopinka** [comment]
$(git_super_status) % echo ${PROMPT}
%B%m%~%b$(git_super_status) %#

**Comment by ctopinka** [comment]
$(git_super_status) % ~/zsh-git-prompt/zshrc.sh 
/Users/christopinka/zsh-git-prompt/zshrc.sh: line 80: syntax error near unexpected token `<'
/Users/christopinka/zsh-git-prompt/zshrc.sh: line 80: `    done < <(__GIT_STATUS_CMD 2>&1)'


This may be expected.

**Comment by ctopinka** [comment]
$(git_super_status) % git status -sb
## indexa-spot...origin/indexa-spot [ahead 2]

**Comment by christopinka** [comment]
Still ok on mojave and bash.

**Comment by thomasrebele** [comment]
The `line 80: syntax error near unexpected token` is indeed "expected". I've added a shebang to prevent it.
Do I understand correctly that the string `$(git_super_status)` appears literally in the prompt? There seems to be a problem with the expansion of the PROMPT. Could you check whether it is really zsh, `ps -p $$`, and which version, `zsh --version`?
Please note that the original zsh-git-prompt and this fork are incompatible.

**Comment by rudifa** [comment]
@thomasrebele Merci pour la version .sh, plus compacte et plus rapide!
@ctopinka  FYI, for me both versions work as advertised.

First I cloned and installed olivierverdier's version - it worked
```
# .zshrc
# from https://github.com/olivierverdier/zsh-git-prompt.git
source ~/GitHub/tools/zsh-git-prompt/zshrc.sh
RPROMPT='$(git_super_status)'    # my preference
```
Today I cloned and installed this version, and modified my .zhrc - it also works and it feels faster
```
# .zshrc
# from https://github.com/zsh-git-prompt/zsh-git-prompt
source ~/GitHub/tools/zsh-git-prompt-sh/zshrc.sh
RPROMPT='$(git_super_status)'
```

My versions:
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
```
```
zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

**Comment by thomasrebele** [comment]
@rudifa, great to hear that this fork works faster than the original repo on your machine. The reason is that the new version only uses shell scripts, avoiding the overhead of starting the Python interpreter.

@ctopinka, does the problem still occur for you?

**Comment by thomasrebele** [comment]
Closing as there has been no reply.
