### ISSUE TITLE
Disable stash display.

### ISSUE THREAD

**Issue by mattrose** [zsh-git-prompt/zsh-git-prompt#14]
Some repos have a huge amount of stashes that I don't want to get rid of, but I don't care to know about all the time.  Is there some easy way of disabling this display that I've missed?

If not, would a PR setting an env var of "ZSH_THEME_GIT_PROMPT_SHOW_STASH" that can toggle this on and off be welcome?

**Comment by thomasrebele** [comment]
Unfortunately there's no such option yet. There has been a similar pull request #13  for completely disabling the status, which is still open. A pull request would be very welcome. If you're interested in making regular contributions, I can add you to the zsh-git-prompt group.

I've recently seen https://github.com/romkatv/powerlevel10k, and maybe it would be interesting to provide a way to use zsh-git-prompt with it? That would be for another ticket, though.
