### ISSUE TITLE
Unable to Customize

### ISSUE THREAD

**Issue by zhao-li** [zsh-git-prompt/zsh-git-prompt#20]
Hi,

Thank you for maintaining this awesome product.

This works:
```
source ~/dots/custom/plugins/zsh-git-prompt/zshrc.sh
PROMPT='%B%m%~%b$(git_super_status) %# '
```

But when I try to customize by overriding `git_super_status`, the prompt no longer works:
```
source ~/dots/custom/plugins/zsh-git-prompt/zshrc.sh

git_super_status() {
  precmd_update_git_vars
  if [ -n "$__CURRENT_GIT_STATUS" ]; then
    STATUS="$ZSH_THEME_GIT_PROMPT_PREFIX$ZSH_THEME_GIT_PROMPT_BRANCH$GIT_BRANCH%{${reset_color}%}"
  fi
  STATUS="$STATUS%{${reset_color}%}$ZSH_THEME_GIT_PROMPT_SUFFIX"
  echo "$STATUS"
}

PROMPT='$(git_super_status)'
```

When I'm stepping through the code, I notice that `__CURRENT_GIT_STATUS` is not set.  Any ideas on what I'm doing wrong or what can be causing `__CURRENT_GIT_STATUS` to not be properly set?

Thank you for your time and help 🙏

PS: If there's any other information I can provide, please let me know and I'll be happy to do so.

**Comment by thomasrebele** [comment]
Hello,

`update_current_git_vars` has to be called at some point. Maybe add it to `git_super_status`? Why do you want to override `git_super_status`?
What's the version of your shell: `$SHELL --version`? What OS are you using?

**Comment by zhao-li** [comment]
Thanks @thomasrebele for helping me out here.  I ended up using this workaround: https://github.com/ohmyzsh/ohmyzsh/issues/10777#issuecomment-1080427021

In case it helps with anything:
I tried to override `git_super_status` because I thought that's what I need to do in order to customize my prompt (from the README):
> You may redefine the function git_super_status (after the source statement) to adapt it to your needs (to change the order in which the information is displayed).

```
$ $SHELL --version
zsh 5.8 (x86_64-apple-darwin21.0)
```

macOS Monterey 12.3

Thanks again for your help 🙏

I'm going to close this as it's no longer an issue for me.
