### ISSUE TITLE
Git numbers truncated

### ISSUE THREAD

**Issue by JaRoSchm** [zsh-git-prompt/zsh-git-prompt#25]
Hi,

Using zsh-git-prompt I have the problem that the numbers appear truncated:
![Screenshot_20220706_123719](https://user-images.githubusercontent.com/6123821/177532154-3bb18508-7171-48e0-9de8-0565d791b2d5.png)
I'm using the default config `PROMPT='%B%m%~%b$(git_super_status) %# '`
How can I fix this?

Thanks in advance!
Jan

**Comment by thomasrebele** [comment]
Hello, this looks indeed quite strange. Maybe that's caused by a too large '+' sign? Maybe if you try a regular plus sign?

```
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[blue]%}+"
```

**Comment by JaRoSchm** [comment]
Hello, thank you, this helped indeed!
For future reference, here the configuration I ended up with for the other symbols:
```
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[blue]%}+"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[green]%}✓"
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[blue]%}%{⚑%G%}"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg[red]%}%{⨯%G%}"
```
