### ISSUE TITLE
I seem to have to source .zshrc for the prompt to update, it does not change with a cd

### ISSUE THREAD

**Issue by ethan-fraser** [zsh-git-prompt/zsh-git-prompt#4]
This was happening for me in Olivier's original too, but I came here because it seems to be an active repo...

**Comment by thomasrebele** [comment]
You might have set your prompt with `PROMPT="...$(git_super_status)..."` (double quotes), instead of `PROMPT='...$(git_super_status)...'` (single quotes).
Could you check with following command?
```
echo $PROMPT
```
The string `$(git_super_status)` should appear in the output.

**Comment by ethan-fraser** [comment]
That was it, thank you
