### ISSUE TITLE
Does not work out of the box in Ubuntu 20.04

### ISSUE THREAD

**Issue by sblask** [zsh-git-prompt/zsh-git-prompt#7]
zsh-git-prompt uses Python by default, but there is no`python` executable in Ubuntu 20.04, only `python2` and `python3`. This causes an error, which is however swallowed in `update_current_git_vars`. So to fix this there are multiple solutions:

- do not swallow the error, which might be a good idea regardless
- change the default from `python` to `shell`
- use `python3` instead of `python`

For reference, if somebody else encounters this problem, you can install https://packages.ubuntu.com/focal/python-is-python3 to get `python` back.

**Comment by thomasrebele** [comment]
Thank you for reporting.

>     * do not swallow the error, which might be a good idea regardless
Indeed, this is a nice-to-have, which would help a lot with debugging. The script is executed while assembling the prompt. I need to check  whether we can output an error message at that point.

>     * change the default from `python` to `shell`
Personally I use `shell`, as it seems to be a bit faster. I'm very much in favor of this solution.

>     * use `python3` instead of `python`
You can specify which python executable to use with `export ZSH_GIT_PROMPT_PYBIN=python3`.

**Comment by sblask** [comment]
Not sure why there are 3 different ways of parsing the output, but I assume that shell should always work, so making it the default would make the most sense to me too. Then if someone wants to use Python, they can and if it doesn't work they know they need to debug Python. I was just very confused: I upgraded my system and suddenly my git prompt didn't work anymore and I had no idea where to start debugging.

**Comment by thomasrebele** [comment]
I've changed the default to shell. At some point I might add the possibility to display the error from the GIT_PROMPT_EXECUTABLE.
