### ISSUE TITLE
Does not show anything in Mac (Catalina)

### ISSUE THREAD

**Issue by mimkorn** [zsh-git-prompt/zsh-git-prompt#8]
Hi. I tried olivierverdier/zsh-git-prompt and that worked, but only upon an opening of a terminal window. It would not update, however, once you make any change of directory or git branch or anything, would stick with the first state.

I cloned your repo, but with this version, I see nothing in the terminal. Any ideas, please?

**Comment by thomasrebele** [comment]
Could you execute `zsh ./zshrc.sh --debug` and post the result?

**Comment by mimkorn** [comment]
Hi, in the meantime I impatiently moved to "ohmyzsh" with p10k theme which already has some git prompt bundled. I'm happy I have sth working. Thanks for reaching out that quick though! If you don't mind, we can close this.

**Comment by meanderis** [comment]
I just installed this on my Catalina system.
`~/test % zsh ~/bin/zshrc.sh --debug
gitstatus: zsh: can't open input file: /Users/<username>/bin/shell/gitstatus.sh
Unexpected output. Check the lines starting with gitstatus:`

I just copied the shell directory into ~/bin/ and everything worked.

**Comment by thomasrebele** [comment]
Indeed, one of the three options (shell, python, haskell) must be available.

Good to hear that you found a "workaround" by using ohmyzsh. Closing the issue.
